// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxbBTWr1z7znsbqTtK-v67uPVdSbvFNI',
    appId: '1:510498498090:web:dfeef8efc5ed0e07150553',
    messagingSenderId: '510498498090',
    projectId: 'akademikbilgierisimagi',
    authDomain: 'akademikbilgierisimagi.firebaseapp.com',
    databaseURL: 'https://akademikbilgierisimagi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'akademikbilgierisimagi.firebasestorage.app',
    measurementId: 'G-Z0EVJGSE02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBq-S020F1vc2w69YrMyOE6w2sKO2idI',
    appId: '1:510498498090:android:c3cbd60214cd37a5150553',
    messagingSenderId: '510498498090',
    projectId: 'akademikbilgierisimagi',
    databaseURL: 'https://akademikbilgierisimagi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'akademikbilgierisimagi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QWuZMUKSwZKHl2RBiTBPyfuIlS5OkEo',
    appId: '1:510498498090:ios:baa74a889d031873150553',
    messagingSenderId: '510498498090',
    projectId: 'akademikbilgierisimagi',
    databaseURL: 'https://akademikbilgierisimagi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'akademikbilgierisimagi.firebasestorage.app',
    iosClientId: '510498498090-ulp073ngo4g4sp1emq7vt9u1ogi47rmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.akademikbilgierisimagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1QWuZMUKSwZKHl2RBiTBPyfuIlS5OkEo',
    appId: '1:510498498090:ios:baa74a889d031873150553',
    messagingSenderId: '510498498090',
    projectId: 'akademikbilgierisimagi',
    databaseURL: 'https://akademikbilgierisimagi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'akademikbilgierisimagi.firebasestorage.app',
    iosClientId: '510498498090-ulp073ngo4g4sp1emq7vt9u1ogi47rmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.akademikbilgierisimagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVxbBTWr1z7znsbqTtK-v67uPVdSbvFNI',
    appId: '1:510498498090:web:d7bc0df7f77dbf05150553',
    messagingSenderId: '510498498090',
    projectId: 'akademikbilgierisimagi',
    authDomain: 'akademikbilgierisimagi.firebaseapp.com',
    databaseURL: 'https://akademikbilgierisimagi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'akademikbilgierisimagi.firebasestorage.app',
    measurementId: 'G-VCH8BYZ0SW',
  );
}
